package com.bawei.dingjianfei20200106.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.dingjianfei20200106.model.dao.Dao1;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DAO1".
*/
public class Dao1Dao extends AbstractDao<Dao1, Void> {

    public static final String TABLENAME = "DAO1";

    /**
     * Properties of entity Dao1.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property A = new Property(0, String.class, "a", false, "A");
    }


    public Dao1Dao(DaoConfig config) {
        super(config);
    }
    
    public Dao1Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DAO1\" (" + //
                "\"A\" TEXT);"); // 0: a
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DAO1\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Dao1 entity) {
        stmt.clearBindings();
 
        String a = entity.getA();
        if (a != null) {
            stmt.bindString(1, a);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Dao1 entity) {
        stmt.clearBindings();
 
        String a = entity.getA();
        if (a != null) {
            stmt.bindString(1, a);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Dao1 readEntity(Cursor cursor, int offset) {
        Dao1 entity = new Dao1( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // a
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Dao1 entity, int offset) {
        entity.setA(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Dao1 entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Dao1 entity) {
        return null;
    }

    @Override
    public boolean hasKey(Dao1 entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
