package com.bawei.dingjianfei20200106.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.dingjianfei20200106.model.dao.Dao1;
import com.bawei.dingjianfei20200106.model.dao.Dao2;

import com.bawei.dingjianfei20200106.database.Dao1Dao;
import com.bawei.dingjianfei20200106.database.Dao2Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dao1DaoConfig;
    private final DaoConfig dao2DaoConfig;

    private final Dao1Dao dao1Dao;
    private final Dao2Dao dao2Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dao1DaoConfig = daoConfigMap.get(Dao1Dao.class).clone();
        dao1DaoConfig.initIdentityScope(type);

        dao2DaoConfig = daoConfigMap.get(Dao2Dao.class).clone();
        dao2DaoConfig.initIdentityScope(type);

        dao1Dao = new Dao1Dao(dao1DaoConfig, this);
        dao2Dao = new Dao2Dao(dao2DaoConfig, this);

        registerDao(Dao1.class, dao1Dao);
        registerDao(Dao2.class, dao2Dao);
    }
    
    public void clear() {
        dao1DaoConfig.clearIdentityScope();
        dao2DaoConfig.clearIdentityScope();
    }

    public Dao1Dao getDao1Dao() {
        return dao1Dao;
    }

    public Dao2Dao getDao2Dao() {
        return dao2Dao;
    }

}
